#!/bin/sh
if test "x${NRNHOME}" = "x" ; then
    NRNHOME="/home/ubuntu/.local/lib/python2.7/site-packages/neuron/.data"
fi
if test "${NEURONHOME}" = "" ; then
    NEURONHOME=${NRNHOME}/share/nrn
    export NEURONHOME
fi
if test "x${NRNBIN}" = "x" ; then
    NRNBIN="/home/ubuntu/.local/bin"
fi
if test "" = "yes" ; then
    NRNIV="${NRNBIN}/nrniv.app/Contents/MacOS/nrniv"
else
    NRNIV="${NRNBIN}/nrniv"
fi
"${NRNIV}" -dll "/media/ubuntu/OS/braingame/nrml_3d/L4_BP_bAC217_1/x86_64/.libs/libnrnmech.so" "$@"
